'use client';
import { AppState, NavPage } from '@/app/page';

interface Props { appState: AppState; updateOptimization: (o: Record<string, unknown>) => void; updateEmergency: (e: Record<string, unknown>) => void; setCurrentPage: (p: NavPage) => void; }

export default function Settings({ appState }: Props) {
  return (
    <div className="page animate-fade-in">
      <div className="page-header">
        <div>
          <h2 className="page-title">Settings</h2>
          <p className="page-subtitle">Configuration for ClearWay AI platform</p>
        </div>
      </div>

      <div className="grid-2">
        <div className="card">
          <div style={{ fontWeight: 700, fontSize: 14, marginBottom: 16 }}>Display Settings</div>
          <div style={{ display: 'flex', flexDirection: 'column', gap: 14 }}>
            {[
              { label: 'Auto-refresh interval', value: '5 seconds (via WebSocket)' },
              { label: 'Theme', value: 'Dark — Quantum' },
              { label: 'Units', value: 'Metric (km/h, kg, g)' },
              { label: 'Timezone', value: 'UTC' },
              { label: 'City', value: 'Tiruppur, Tamil Nadu, India' },
              { label: 'Network junctions', value: '6 (J1–J6)' },
            ].map(({ label, value }) => (
              <div key={label} style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '8px 0', borderBottom: '1px solid var(--border-subtle)' }}>
                <span style={{ fontSize: 13, color: 'var(--text-secondary)' }}>{label}</span>
                <span style={{ fontSize: 13, fontWeight: 600, color: 'var(--text-primary)' }}>{value}</span>
              </div>
            ))}
          </div>
        </div>

        <div className="card">
          <div style={{ fontWeight: 700, fontSize: 14, marginBottom: 16 }}>Data Labels Reference</div>
          <div style={{ display: 'flex', flexDirection: 'column', gap: 10 }}>
            {[
              { badge: 'SIMULATED', class: 'badge-simulated', desc: 'Generated by software, no real sensor/device' },
              { badge: 'ESTIMATED', class: 'badge-estimated', desc: 'Computed from emission factors, not measured' },
              { badge: 'QUANTUM SIMULATOR', class: 'badge-quantum', desc: 'Qiskit Aer statevector — NOT real quantum hardware' },
              { badge: 'DEMO', class: 'badge-blue', desc: 'Synthetic demo data, Tiruppur-inspired' },
              { badge: 'AI PREDICTION', class: 'badge-cyan', desc: 'ML/AI forecast, not guaranteed' },
              { badge: 'SIMULATED RADIO', class: 'badge-amber', desc: 'NOT real police radio — TTS voice only' },
            ].map(({ badge, class: cls, desc }) => (
              <div key={badge} style={{ display: 'flex', alignItems: 'flex-start', gap: 12 }}>
                <span className={`badge ${cls}`} style={{ flexShrink: 0, marginTop: 2 }}>{badge}</span>
                <span style={{ fontSize: 12, color: 'var(--text-secondary)', lineHeight: 1.5 }}>{desc}</span>
              </div>
            ))}
          </div>
        </div>

        <div className="card">
          <div style={{ fontWeight: 700, fontSize: 14, marginBottom: 16 }}>Backend API Endpoints</div>
          <div style={{ display: 'flex', flexDirection: 'column', gap: 6 }}>
            {[
              'GET /traffic/live', 'GET /intersections', 'POST /optimization/run',
              'POST /emergency/activate', 'POST /siren/detect/{id}', 'GET /pollution/estimates',
              'POST /simulation/run', 'POST /ai/chat', 'GET /predictions',
              'POST /events', 'POST /reports/generate', 'WS  /ws/traffic',
            ].map(ep => (
              <div key={ep} style={{ fontFamily: 'JetBrains Mono, monospace', fontSize: 11, color: 'var(--accent-cyan)', padding: '4px 8px', background: 'var(--bg-secondary)', borderRadius: 4 }}>{ep}</div>
            ))}
          </div>
          <div style={{ marginTop: 12, fontSize: 12, color: 'var(--text-secondary)' }}>
            Full interactive docs at <a href="http://localhost:8000/docs" target="_blank" style={{ color: 'var(--accent-cyan)' }}>http://localhost:8000/docs</a>
          </div>
        </div>

        <div className="card">
          <div style={{ fontWeight: 700, fontSize: 14, marginBottom: 16 }}>About ClearWay AI</div>
          <div style={{ fontSize: 13, color: 'var(--text-secondary)', lineHeight: 1.8 }}>
            <p style={{ marginBottom: 12 }}><strong style={{ color: 'var(--text-primary)' }}>ClearWay AI</strong> is a quantum-enhanced adaptive urban traffic optimization platform combining:</p>
            <ul style={{ paddingLeft: 20, display: 'flex', flexDirection: 'column', gap: 6 }}>
              {[
                'FastAPI Python backend — the core product',
                'QUBO/QAOA quantum signal optimization (Qiskit Aer)',
                'Emergency green corridor routing (NetworkX Dijkstra)',
                'Siren detection pipeline (MFCC + SVC + TTS dispatch)',
                'Computer vision vehicle detection (OpenCV)',
                'AI traffic predictions (pattern-based ML)',
                'Pollution estimation (emission factor models)',
                'Discrete-event traffic simulation',
                'Gemini-powered AIRA assistant',
                'Real-time WebSocket data hub',
              ].map(f => <li key={f} style={{ color: 'var(--text-secondary)', fontSize: 12 }}>• {f}</li>)}
            </ul>
          </div>
        </div>
      </div>
    </div>
  );
}
